### ISSUE TITLE
default size font

### ISSUE THREAD

**Issue by sidongfu** [MichalKononenko/UWWorkTermReport#31]
Changing the font size in `\documentclass[11pt]{workreport}` doesn't have effect in the text. 
Currently, the default font size is 10, which should be 11pt according the marking guidelines. 

EDIT: I replaced the quotes with the triple backtick for delineating code in [GFM](https://guides.github.com/features/mastering-markdown/)

**Comment by MichalKononenko** [comment]
I've opened up ShareLaTeX on my Windows 10 partition. I'm going to copy over `workreport.cls` and the relevant `.sty` files into the page and compile it.

**Comment by MichalKononenko** [comment]
@sidongfu, is this similar to what you did to get your ShareLaTeX running?

**Comment by MichalKononenko** [comment]
I have an idea on how to fix it. Instead of loading `mathptmx` and loading the Times font, use the `fontspec` package, and load Times New Roman using this. This would be similar to this [StackExchange Post](http://tex.stackexchange.com/questions/67768/times-new-roman-font). 

``` tex
\usepackage{fontspec}
\setmainfont{Times New Roman}
```

The trouble is that it might not compile with `pdflatex`, requiring `xelatex` or `LuaLaTeX`  instead
